import React, { useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { apiFetch } from '../../src/api';

export default function NewRunScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ deviceId?: string; roomId?: string }>(); const [question, setQuestion] = useState('The wall display is offline after a power interruption. What should I check?'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit() { setBusy(true); setError(''); try { const response = await apiFetch('/api/v1/runs', { method: 'POST', headers: { 'idempotency-key': `mobile-${Date.now()}` }, body: JSON.stringify({ roomId: params.roomId ?? '20000000-0000-4000-8000-000000000001', deviceId: params.deviceId ?? '30000000-0000-4000-8000-000000000001', question, mediaIds: [] }) }); const body = await response.json(); if (!response.ok) throw new Error(body.detail ?? 'Run could not be queued'); router.push(`/runs/${body.runId}`); } catch (value) { setError(value instanceof Error ? value.message : 'Run failed'); } finally { setBusy(false); } }
  return <View style={styles.container}><Text style={styles.title}>Ask the copilot</Text><Text style={styles.context}>Room and device IDs are carried by navigation state; the server rebinds them to the session tenant.</Text><TextInput style={styles.textArea} multiline value={question} onChangeText={setQuestion} placeholder="Describe the symptom" placeholderTextColor="#64748b" /><Text style={styles.note}>Image and voice adapters are opt-in; raw media is never cached offline.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}<TouchableOpacity style={styles.button} onPress={submit} disabled={busy}>{busy ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Queue diagnosis</Text>}</TouchableOpacity></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#090d16', padding: 16 }, title: { color: '#f8fafc', fontSize: 24, fontWeight: '700' }, context: { color: '#94a3b8', marginVertical: 14 }, textArea: { minHeight: 130, backgroundColor: '#1e293b', color: '#f8fafc', borderRadius: 8, padding: 14, textAlignVertical: 'top' }, note: { color: '#64748b', fontSize: 12, marginVertical: 14 }, button: { backgroundColor: '#2563eb', padding: 16, borderRadius: 8, alignItems: 'center' }, buttonText: { color: '#fff', fontWeight: '700' }, error: { color: '#fb7185', marginBottom: 12 } });
